#!/usr/bin/env python3
"""DSX v0.1-draft -- sampling conformance vectors (spec section 4).

Run:  python3 conformance/run_sampling_checks.py

This harness does not implement section 4. It drives `tools/dsx_sample.py` and
compares its canonical CSV (section 4.4.5) byte for byte against the expected
files in `conformance/sampling/`.

The separation is deliberate. The expected values of the `analytic` cases were
computed by hand from the formulas in the specification, before the reference
implementation existed, and the derivation is shown in
`conformance/sampling/INDEX.md`. A suite generated by the implementation it
tests proves only that the implementation equals itself.
"""
import pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

try:
    import dsx_sample
except ImportError as e:                                    # pragma: no cover
    sys.exit(f"tools/dsx_sample.py not importable: {e}")

VEC = ROOT / "conformance" / "sampling"

# case, light program (or None), rate_hz, duration_ms, provenance class
CASES = [
    ("a1-bezier",         None,            4, 1000, "analytic"),
    ("a2-light",          "a2-light",      4, 4000, "analytic"),
    ("a3-until-next",     None,            2, 2000, "analytic"),
    ("a4-since-previous", None,            2, 2000, "analytic"),
    ("a5-cubic",          None,            2, 3000, "analytic"),
]

fail = 0
print("DSX sampling vectors (spec section 4)\n")

for name, light, rate, dur, kind in CASES:
    traj = VEC / f"{name}.traj.json"
    lightp = VEC / f"{light}.light.json" if light else None
    expected_p = VEC / f"{name}.expected.csv"

    for p in (traj, expected_p) + ((lightp,) if lightp else ()):
        if not p.exists():
            print(f"FAIL  {name:20s} missing file: {p.relative_to(ROOT)}")
            fail += 1
            break
    else:
        try:
            got = dsx_sample.sample_to_csv(
                dsx_sample.load_resource(traj),
                dsx_sample.load_resource(lightp) if lightp else None,
                rate, dur,
            )
        except Exception as e:
            print(f"FAIL  {name:20s} [{kind}] raised {type(e).__name__}: {e}")
            fail += 1
            continue

        want = expected_p.read_text()
        if got == want:
            print(f"PASS  {name:20s} [{kind}] {rate} Hz / {dur} ms")
        else:
            fail += 1
            print(f"FAIL  {name:20s} [{kind}] output differs")
            gl, wl = got.splitlines(), want.splitlines()
            if len(gl) != len(wl):
                print(f"        row count: got {len(gl)}, expected {len(wl)}")
            for i, (a, b) in enumerate(zip(gl, wl)):
                if a != b:
                    print(f"        line {i+1}:")
                    print(f"          expected  {b}")
                    print(f"          got       {a}")

n_analytic = sum(1 for c in CASES if c[4] == "analytic")
print(f"\n{len(CASES) - fail}/{len(CASES)} vectors pass "
      f"({n_analytic} of {len(CASES)} are hand-computed, not generated)")

# ---------------------------------------------------------------------------
# Negative and side-effect checks found during the 2026-08-15 audit of
# AMBIGUITIES (see CHANGELOG.md). Proving a rule fires is worth as much as
# proving the happy path, and a REJECT with no test is a claim, not a fact.
# ---------------------------------------------------------------------------
import io, contextlib, json as _json

print("\nOther section-4 rules")

# 4.5.2: duty is REQUIRED on a strobe op, no default. Rejected at load time.
try:
    dsx_sample.load_resource(VEC / "reject-strobe-no-duty.light.json")
    print("FAIL  strobe without duty            should have raised DsxError")
    fail += 1
except dsx_sample.DsxError as e:
    print(f"PASS  strobe without duty            rejected: {e}")

# Same rule, at schema level -- resource.schema.json must agree with the code.
try:
    import jsonschema
    from referencing import Registry, Resource
    schema_dir = ROOT / "schema"
    res = []
    for f in sorted(schema_dir.glob("*.json")):
        d = _json.loads(f.read_text())
        r = Resource.from_contents(d)
        res.append((d["$id"], r))
        res.append((f.name, r))
    reg = Registry().with_resources(res)
    schema = _json.loads((schema_dir / "resource.schema.json").read_text())
    V = jsonschema.Draft202012Validator(schema, registry=reg)
    doc = _json.loads((VEC / "reject-strobe-no-duty.light.json").read_text())
    errs = list(V.iter_errors(doc))
    if errs:
        print(f"PASS  strobe without duty (schema)   rejected: {errs[0].message}")
    else:
        print("FAIL  strobe without duty (schema)   resource.schema.json accepted it")
        fail += 1
except ImportError:
    print("SKIP  strobe without duty (schema)   jsonschema/referencing not installed")

# 4.4.5: a channel beyond R/G/B MUST be reported as a WARN-class finding when
# the canonical reduction drops it, not dropped silently.
buf = io.StringIO()
with contextlib.redirect_stderr(buf):
    dsx_sample.sample_to_csv(
        dsx_sample.load_resource(VEC / "a1-bezier.traj.json"),
        dsx_sample.load_resource(VEC / "reject-rgbw-drop-warns.light.json"),
        4, 1000,
    )
if "WARN" in buf.getvalue() and "'W'" in buf.getvalue():
    print(f"PASS  RGBW channel dropped           warns: {buf.getvalue().strip()}")
else:
    print(f"FAIL  RGBW channel dropped           no WARN printed (got: {buf.getvalue()!r})")
    fail += 1

sys.exit(1 if fail else 0)
