#!/usr/bin/env python3
"""Render spec/C-profile-matrix.md from profiles/profile-matrix.json.

Run:  python3 tools/gen_profile_matrix.py --write

The table is generated for one reason: a hand-maintained matrix and a schema
drift apart, quietly, and the reader has no way to tell which of the two is
lying. Here the JSON is normative, the schema is checked against it by
`conformance/check_profiles.py`, and this file only renders.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MATRIX_PATH = ROOT / "profiles" / "profile-matrix.json"
OUT_PATH = ROOT / "spec" / "C-profile-matrix.md"

SYMBOL = {
    "REQUIRED": "**MUST**",
    "OPTIONAL": "MAY",
    "FORBIDDEN": "**MUST NOT**",
    "CONDITIONAL": "cond.",
}

HEADER = """# Appendix C -- Profile matrix (normative)

*Generated from `profiles/profile-matrix.json` by `tools/gen_profile_matrix.py`.
Do not edit this file; edit the JSON. `conformance/check_profiles.py` proves the
two agree, checks every cell against `schema/dsx.schema.json`, and checks the
reference files in `examples/` against their own row.*

Sections 1.3, 2.3, 3, 4.2.5, 7 and 10.9 each state profile applicability for the
members they introduce. This appendix is the single place where all of it is
collected, and it is normative: where a cell here and a sentence elsewhere
disagree, that is a defect, and `check_profiles.py` is where it surfaces.

**Reading the table.** `MUST` -- the member is required in a file declaring that
profile; its absence is REJECT (5.6). `MAY` -- optional, but a reader of that
profile MUST understand it when present. `MUST NOT` -- its presence is REJECT; a
file that needs the member declares a higher profile. `cond.` -- a condition in
the notes decides, not the profile alone.

Profiles are cumulative: no member goes from `MUST` at a lower profile to
`MUST NOT` at a higher one. The reverse -- `MUST` at L0 relaxing to `MAY` at L1
-- does occur, and `drones[].trajectory_sampled` is the case: L0 has no other
way to carry a trajectory, while above L0 the sampled track is a derived cache.

"""

FOOTER = """
## Profiles in one line each

**L0 Sampled** -- positions and RGB, sampled. The floor of the format: every
conformant file reduces to it (1.4), and an L0 consumer needs no interpolation,
no device model and no safety machinery.

**L1 Show** -- adds segment trajectories, light programs, device-profile binding
and the show-level safety envelope. This is the profile a designer works in.

**L2 Production** -- adds yaw, payloads, rotation and multi-wave operations,
termination policy, provenance and signatures. This is the profile an operator
files with an authority.
"""


def render(matrix: dict) -> str:
    out = [HEADER]
    out.append(f"Matrix version {matrix['matrix_version']} "
               f"for DSX {matrix['dsx_version']}.\n")

    footnotes = []
    rows = ["| Member | L0 | L1 | L2 | § | |",
            "| --- | :---: | :---: | :---: | :---: | :---: |"]
    for m in matrix["members"]:
        marker = ""
        if m.get("condition") or m.get("note"):
            footnotes.append(m)
            marker = f"[{len(footnotes)}](#c{len(footnotes)})"
        path = m["path"]
        if path.startswith("resource:"):
            path = path.split(":", 1)[1] + " *(resource)*"
        rows.append(
            f"| `{path}` | {SYMBOL[m['L0']]} | {SYMBOL[m['L1']]} | "
            f"{SYMBOL[m['L2']]} | {m['section']} | {marker} |"
        )
    out.append("\n".join(rows))

    out.append("\n## Notes\n")
    for i, m in enumerate(footnotes, 1):
        path = m["path"].split(":", 1)[-1]
        out.append(f'<a id="c{i}"></a>**{i}. `{path}`**  ')
        if m.get("condition"):
            out.append(f"*Condition:* {m['condition']}  ")
        if m.get("note"):
            out.append(m["note"])
        out.append("")

    out.append(FOOTER)
    return "\n".join(out)


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    text = render(json.loads(MATRIX_PATH.read_text()))
    if "--write" in argv:
        OUT_PATH.write_text(text)
        print(f"wrote {OUT_PATH.relative_to(ROOT)} ({len(text)} bytes)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
